# Generated by Django 4.1.3 on 2022-12-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Principal', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
